# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGraphicsOpacityEffect


class Ui_Dialog(object):

    def fade(self, widget, duration=1000):
        self.effect = QGraphicsOpacityEffect()
        widget.setGraphicsEffect(self.effect)

        self.animation = QtCore.QPropertyAnimation(self.effect, b"opacity")
        self.animation.setDuration(duration)
        self.animation.setStartValue(1)
        self.animation.setEndValue(0)
        self.animation.start()

    def unfade(self, widget, duration=1000):
        self.effect = QGraphicsOpacityEffect()
        widget.setGraphicsEffect(self.effect)

        self.animation = QtCore.QPropertyAnimation(self.effect, b"opacity")
        self.animation.setDuration(duration)
        self.animation.setStartValue(0)
        self.animation.setEndValue(1)
        self.animation.start()
    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 766)
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1201, 801))
        self.bgwidget.setObjectName("bgwidget")
        self.bglabel = QtWidgets.QLabel(self.bgwidget)
        self.bglabel.setGeometry(QtCore.QRect(0, 0, 1201, 801))
        self.bglabel.setText("")
        self.bglabel.setPixmap(QtGui.QPixmap("../Images/background.png"))
        self.bglabel.setScaledContents(True)
        self.bglabel.setObjectName("bglabel")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 140, 511, 61))
        self.label_2.setStyleSheet("font: 36pt \"MS Sans Serif\";color:rgb(255, 255, 255)\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.login = QtWidgets.QPushButton(self.bgwidget)
        self.login.setGeometry(QtCore.QRect(640, 620, 301, 61))
        self.login.setStyleSheet("\n"
"QPushButton {\n"
"border-radius:20px;\n"
"font: 75 18pt \"MS Shell Dlg 2\"; \n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(10, 4, 121)\n"
"\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(79, 238, 0, 255), stop:1 rgba(0, 170, 0, 255))\n"
"}")
        self.login.setObjectName("login")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(400, 10, 391, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Images/logo.png"))
        self.label.setScaledContents(False)

        self.label.setObjectName("label")
        self.user_name = QtWidgets.QLineEdit(self.bgwidget)
        self.user_name.setGeometry(QtCore.QRect(390, 410, 421, 51))
        self.user_name.setStyleSheet("\n"
"\n"
"QLineEdit {\n"
"background-color:rgba(0,0,0,0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 2px solid white;\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"border: 2px solid rgb(0, 229, 0);\n"
"}\n"
"\n"
"")
        self.user_name.setText("")
        self.user_name.setObjectName("user_name")
        self.password = QtWidgets.QLineEdit(self.bgwidget)
        self.password.setGeometry(QtCore.QRect(390, 520, 421, 51))
        self.password.setStyleSheet("\n"
"\n"
"QLineEdit {\n"
"background-color:rgba(0,0,0,0);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"border: 2px solid white;\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QLineEdit::focus {\n"
"border: 2px solid rgb(0, 229, 0);\n"
"}\n"
"\n"
"")
        self.password.setObjectName("password")
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 385, 71, 21))
        self.label_3.setStyleSheet("color: white;\n"
"font: 15pt \"Tw Cen MT\";")
        self.label_3.setObjectName("label_3")
        self.faceid = QtWidgets.QPushButton(self.bgwidget)
        self.faceid.setGeometry(QtCore.QRect(510, 240, 191, 141))
        self.faceid.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.faceid.setStyleSheet("background-color:rgb(10, 4, 121);\n"
"border-radius:20px;")
        self.faceid.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/face_recognition.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.faceid.setIcon(icon)
        self.faceid.setIconSize(QtCore.QSize(120, 120))
        self.faceid.setObjectName("faceid")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 500, 81, 16))
        self.label_4.setStyleSheet("color: white;\n"
"font: 15pt \"Tw Cen MT\";")
        self.label_4.setObjectName("label_4")
        self.register_label = QtWidgets.QPushButton(self.bgwidget)
        self.register_label.setGeometry(QtCore.QRect(300, 620, 301, 61))
        self.register_label.setStyleSheet("\n"
"QPushButton {\n"
"border-radius:20px;\n"
"font: 75 18pt \"MS Shell Dlg 2\"; \n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(10, 4, 121)\n"
"\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(0, 85, 255, 255))\n"
"}")
        self.register_label.setObjectName("register_label")
        self.error = QtWidgets.QLabel(self.bgwidget)
        self.error.setGeometry(QtCore.QRect(390, 580, 361, 21))
        self.error.setStyleSheet("\n"
"font: 10pt \"Tw Cen MT\";color:blue;")
        self.error.setText("")
        self.error.setObjectName("error")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # # Everything starts off invisible
        # self.fade(self.login, 0)
        # self.fade(self.user_name, 0)
        # self.fade(self.password, 0)
        # self.fade(self.faceid, 0)
        # self.fade(self.label, 0)
        # self.fade(self.label_2, 0)
        # self.fade(self.label_3, 0)
        # self.fade(self.label_4, 0)
        # self.fade(self.password, 0)
        # self.fade(self.register_label, 0)
        # # self.fade(self.error, 0)

        # # Slowly fade in
        # self.unfade(self.label, 1000)
        # import time
        # time.sleep(1)
        # self.unfade(self.label_2, 2000)

        self.fade(self.bgwidget, 0)
        self.unfade(self.bgwidget, 2500)

        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "REGISTER OR LOGIN"))
        self.login.setText(_translate("Dialog", "LOGIN"))
        self.label_3.setText(_translate("Dialog", "Login-Id"))
        self.label_4.setText(_translate("Dialog", "Password"))
        self.register_label.setText(_translate("Dialog", "REGISTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
